# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have
#  python3 -m runx.runx scripts/train_rtisrail22.yml -i

# CUDA_VISIBLE_DEVICES="4,5,6,7" python3 -m runx.runx scripts/train_rtisrail22.yml -i

CMD: "python3 -m torch.distributed.launch --nproc_per_node=4 train.py"

HPARAMS: [
  {
   dataset: rtisrail22,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   gblur: true,
   brt_aug: true,
   crop_size: "1080,1920",
   bs_trn: 1,
   poly_exp: 2,
   lr: 7e-5,
   rmi_loss: true,
   max_epoch: 1000,
   n_scales: ['0.5,1.0,1.5'],
   supervised_mscale_loss_wt: 0.05,
   snapshot: "checkpoints/rs19_cityscapes_ep98_miou_0.7385.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: "logs/rr22/rtisrail22_train_4",
   RUNX.TAG: '{arch}',
  },
]