# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have

CMD: "python -m torch.distributed.launch --nproc_per_node=4 train.py"

HPARAMS: [
  {
   dataset: railsem19,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   gblur: true,
   brt_aug: true,
   crop_size: "1080,1920",
   bs_trn: 1,
   poly_exp: 2,
   lr: 5e-4,
   rmi_loss: true,
   max_epoch: 300,
   n_scales: ['0.5,1.0,2.0'],
   supervised_mscale_loss_wt: 0.05,
   snapshot: "/home/stanik/repos/semantic-segmentation/checkpoints/cityscapes_trainval_ocr.HRNet_Mscale_nimble-chihuahua.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: "logs/rs19/cityscapes_sota_rs19_finetune_bs_1",
   RUNX.TAG: '{arch}',
  },
]