# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have

# CUDA_VISIBLE_DEVICES="4,5,6,7" python3 -m runx.runx scripts/train_flame.yml -i

CMD: "python3 -m torch.distributed.launch --nproc_per_node=4 train.py"

HPARAMS: [
  {
   dataset: flame,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   gblur: true,
   brt_aug: true,
   crop_size: "1080,1920",
   bs_trn: 1,
   poly_exp: 2,
   lr: 5e-5,
   rmi_loss: true,
   max_epoch: 150,
   n_scales: ['1.0,2.0,2.5'],
   supervised_mscale_loss_wt: 0.1,
   snapshot: "/home/stanik/repos/semantic-segmentation/semantic-segmentation/checkpoints/cityscapes_trainval_ocr.HRNet_Mscale_nimble-chihuahua.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: "logs/flame/1",
   RUNX.TAG: '{arch}',
  },
]